[package]
name = "dcli"
version = "0.1.0"
authors = ["Mike Chambers <mikechambers@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version="0.10.8", features=["json"] }
serde = "1.0.117"
serde_derive = "1.0.117"