[workspace]
members = ["dclia", "dclic", "dclics", "dclim", "dclims", "dclis", "dcliah", "dclitime", "dclias","dcliad"]

#https://github.com/johnthagen/min-sized-rust
[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
